### ISSUE TITLE
This library seems to interfere with pyautogui

### ISSUE THREAD

**Issue by Avnsx** [ReggX/pydirectinput_rgx#5]
Even just importing press from pydirectinput_rgx or core pydirectinput from @learncodebygaming like in the following example:
```python
from pydirectinput import press

import pyautogui
pyautogui.moveTo(1, 5, 0)
```
causes:
```python
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\pyautogui_test.py", line 6, in <module>
    pyautogui.moveTo(1, 5, 0)
  File "C:\Program Files\Python\Lib\site-packages\pyautogui\__init__.py", line 593, in wrapper
    failSafeCheck()
  File "C:\Program Files\Python\Lib\site-packages\pyautogui\__init__.py", line 1733, in failSafeCheck
    if FAILSAFE and tuple(position()) in FAILSAFE_POINTS:
                          ^^^^^^^^^^
  File "C:\Program Files\Python\Lib\site-packages\pyautogui\__init__.py", line 767, in position
    posx, posy = platformModule._position()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python\Lib\site-packages\pyautogui\_pyautogui_win.py", line 344, in _position
    ctypes.windll.user32.GetCursorPos(ctypes.byref(cursor))
ctypes.ArgumentError: argument 1: TypeError: expected LP__POINT instance instead of pointer to POINT
```

Apparently years ago this was a bug in pyautogui (https://github.com/pywinauto/pywinauto/issues/788), but according to the issue ticket it was fixed, somehow importing pydirectinput_rgx in that specific way "unfixes" it and I'm not sure why.

using py ``pyautogui Version: 0.9.54`` and ``pydirectinput_rgx Version: 2.0.7`` on python 3.11.2 with Windows 11 - x64 bit

Edit: According to this issue https://github.com/moses-palmer/pystray/issues/93#issue-912959887 you need to create a new instance of windll or something 🤷🏼

**Comment by ReggX** [comment]
Yes, it seems like creating a new instance of windll does stop those two packages from interfering with each other.

I will push a new version soon.
